#!/usr/bin/env python3
"""Folder -> project metadata. Edit this file to change how tiles are labelled."""

# folder (as it appears under "Microfiche Photos") -> (Display name, Category, Kind)
PROJECTS = {
    "Apparel":                      ("Apparel",                    "Objects",  "garment"),
    "Apparel/AuraCadet":            ("Aura Cadet",                 "Objects",  "garment"),
    "Campsorted":                   ("CampSorted",                 "Web",      "deck"),
    "Card_Pngs":                    ("ELECTION",                   "Games",    "card"),
    "Election Files for Portfolio": ("ELECTION",                   "Games",    "campaign"),
    "DUMP":                         ("The Dump Show",              "Games",    "screen"),
    "Emiko and the Night House":    ("Emiko and the Night House",  "Books",    "page"),
    "Epsilon":                      ("Epsilon",                    "Web",      "screen"),
    "Feelabit":                     ("Feelabit",                   "Apps",     "screen"),
    "Halal 100":                    ("Halal 100",                  "Apps",     "mark"),
    "Home Page":                    ("youmightfindit.com",         "Web",      "screen"),
    "Hue Hunt":                     ("Hue Hunt",                   "Apps",     "screen"),
    "Misc.":                        ("Miscellany",                 "Objects",  "image"),
    "Nearside":                     ("Nearside",                   "Apps",     "screen"),
    "Politics":                     ("The Voting Report Card",     "Web",      "screen"),
    "Quickfire":                    ("Quickfire",                  "Web",      "screen"),
    "Rainbow Cobra":                ("Rainbow Cobra",              "Games",    "screen"),
    "rainbow cobra photos":         ("Rainbow Cobra",              "Games",    "screen"),
    "The Flush 50":                 ("The Flush 50",               "Apps",     "screen"),
    "Two Dots and a Line":          ("Two Dots and a Line",        "Games",    "screen"),
    "URL Sorted":                   ("URL Sorted",                 "Web",      "screen"),
    "Words":                        ("Words",                      "Writing",  "text"),
    "Yume Nikki":                   ("Yume Nikki",                 "Web",      "screen"),
}

# Where a work goes when you click it, once you're zoomed in. Keyed by the display name in
# PROJECTS above. A project with no entry here simply isn't clickable.
LINKS = {
    "CampSorted":               "https://youmightfindit.com/portfolio/campsorted",
    "Aura Cadet":               "https://youmightfindit.com/portfolio/auracadet",
    "Apparel":                  "https://youmightfindit.com/portfolio/auracadet",
    "ELECTION":                 "https://youmightfindit.com/portfolio/election",
    "Emiko and the Night House": "https://youmightfindit.com/portfolio/emiko",
    "Hue Hunt":                 "https://youmightfindit.com/portfolio/hue-hunt",
    "The Voting Report Card":   "https://youmightfindit.com/portfolio/voting",
    "Feelabit":                 "https://youmightfindit.com/portfolio/innerloop",   # earlier name
    "Old Writings":             "https://youmightfindit.com/portfolio/the-tasting-menu-writing-samples",
    "Words":                    "https://youmightfindit.com/portfolio/the-tasting-menu-writing-samples",
    "Halal 100":                "https://youmightfindit.com/apps",
    "Nearside":                 "https://youmightfindit.com/apps",
    "Rainbow Cobra":            "https://youmightfindit.com/apps",
    "The Flush 50":             "https://youmightfindit.com/apps",
}

# Source images to leave out of the archive entirely.
EXCLUDE = [
    "Quickfire/01-app-icon-512.png",     # the green Q — off-brand
    "Quickfire/02-app-icon-192.png",     # same artwork, exported twice
]

# Hero images: get a larger block in the mosaic. Matched on the source path suffix.
HEROES = [
    "Emiko and the Night House/emiko_page_01.png",
    "DUMP/02-title-menu-dmg.png",
    "Two Dots and a Line/01-title-screen.png",
    "Rainbow Cobra/01-key-art-splash.png",
    "The Flush 50/01-app-icon-master-4797px.png",
    "Feelabit/01-app-icon-rabbit-1024.png",
    "Halal 100/Halal_100-02_forbiggerimages.png",
    "Hue Hunt/03-app-icon-source.png",
    "Home Page/01-sunset-hero.png",
    "Home Page/03-playlist-open.png",
    "URL Sorted/01-extension-icon-128-4x.png",
    "Nearside/01-logo-256-4x.png",
    "Yume Nikki/01-nexus-hub.png",
    "Election Files for Portfolio/election_kickstarter_hero2.jpg",
    "Misc./nouselesstech-11.png",
    "Words/Screen Shot 2020-11-20 at 11.25.11 AM.jpeg",
    "Apparel/AuraCadet/AC_ShortSleeve_Black_03.jpg",  # the broken-heart X mark
]

# ELECTION is a real card game and every card has a real name printed on it. Read off
# the artwork (see sheets/cards_*.png). Without this the two file batches both number
# from 01, so 37 labels pointed at two different cards each — worse than bland, wrong.
TITLES = {
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-01.png": "Ya Got Chads…",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-02.png": "Indecision",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-03.png": "25th Hour Error",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-04.png": "Squiggy",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-05.png": "The Sage",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-06.png": "Scarlet Flyer",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-07.png": "Mobius",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-08.png": "Bob",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-09.png": "The Dude",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-10.png": "Multidimensional Hand",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-11.png": "Ca-Me-Leon",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-12.png": "Crystal Ball",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-13.png": "Tea Leaves",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-14.png": "Silent Sully",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-15.png": "Quiet Casper",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-16.png": "Monk-ey",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-17.png": "The Librarian",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-18.png": "Letdown Larry",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-19.png": "Pensive Penny",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-20.png": "Hugh the Unhappy Human",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-21.png": "Zombz",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-22.png": "Trent",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-23.png": "Alphabet Soup",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-24.png": "Make Me Laugh Clown",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-25.png": "Game Theory",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-26.png": "Filabuster",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-27.png": "Cyber Attack",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-28.png": "Global Warming",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-29.png": "Black Hole",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-30.png": "Final Debate · Economic Policies",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-31.png": "Final Debate · Healthcare",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-32.png": "Final Debate · Climate Change",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-33.png": "Final Debate · Foreign Policy",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-34.png": "Final Debate · Education",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-35.png": "Final Debate · National Security",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-36.png": "Final Debate · Technology",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-37.png": "Final Debate · Affordable Housing",
    "Card_Pngs/Election_poker-size_MAY_for-jpegs1-39.png": "Recount",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-01.png": "Mecha-Abe Lincoln’s Hat",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-02.png": "Mecha-Abe Lincoln’s Face",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-03.png": "Mecha-Abe Lincoln’s Ear",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-04.png": "Mecha-Abe Lincoln’s Bowtie",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-05.png": "Mecha-Abe Lincoln’s Shoulder",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-06.png": "The Present",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-07.png": "Ice-Cream Bribes",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-08.png": "Jelly Delivery",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-09.png": "A Bit of Good",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-10.png": "You’re a Liar!",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-11.png": "You’re a Liar!",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-12.png": "You’re a Liar!",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-13.png": "You’re a Liar!",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-14.png": "You’re a Liar!",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-15.png": "You’re a Liar!",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-16.png": "Feeling Sneaky",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-17.png": "Catch Me If You Can",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-18.png": "Hide and Seek",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-19.png": "The Ghost of George Washington",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-20.png": "Angry Zombie Horde",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-21.png": "Arthur",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-22.png": "I’m a Hugger",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-23.png": "Good Buddy Ol’ Pal",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-24.png": "Matching Energy",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-25.png": "Sharing is Caring",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-26.png": "Fairytale Land",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-27.png": "Sunglasses at Night",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-28.png": "Talk to the Hand",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-29.png": "Gasp!",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-30.png": "Gasp!",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-31.png": "Gasp!",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-32.png": "Phone Banking",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-33.png": "Finders Keepers",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-34.png": "Daddy’s Money",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-35.png": "Animal Farm",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-36.png": "Camerai Idol",
    "Card_Pngs/Election_poker-size_MAY_for-pngs2-37.png": "Mr. Roboto",
    "Election Files for Portfolio/247de070b9708e62e31503ba2eb6607c_original.avif": "Kickstarter · Welcome to ELECTION",
    "Election Files for Portfolio/33403f9874a1ebad1242d2cf16798cc0_original.avif": "Kickstarter · The Full Deck",
    "Election Files for Portfolio/55689aaa18dd763580176b5100db917a_original.avif": "Kickstarter · How to Play",
    "Election Files for Portfolio/7801005ac6d74aedd1d6807e75004496_original.png": "Kickstarter · Deck Components",
    "Election Files for Portfolio/c85d0176d0b8c0152e18ffb27cdcedad_original.avif": "Kickstarter · The Final Debate",
    "Election Files for Portfolio/election_kickstarter_hero2.jpg": "Take Over the Galaxy, One Voter at a Time",
    "Election Files for Portfolio/fe0f2add9b3b0bfc4d2229455c5608d8_original.avif": "Kickstarter · Card Gallery",
}

# Filename fragment -> nicer title fragment
RENAME = [
    ("emiko_page_",              "Page "),
    ("AC_K_Hoodie_",             "Kids Hoodie · "),
    ("AC_W_Hoodie_",             "Womens Hoodie · "),
    ("AC_Hoodie_",               "Hoodie · "),
    ("AC_ShortSleeve_",          "Tee · "),
    ("Election_poker-size_MAY_for-jpegs1-", "Card "),
    ("Election_poker-size_MAY_for-pngs2-",  "Card "),
    ("Slide",                    "Slide "),
]
